unstable_features = true
edition = "2024"
fn_single_line = true
brace_style = "PreferSameLine"
skip_macro_invocations = ["All"]
hex_literal_case = "Upper"
use_field_init_shorthand = true
imports_granularity = "Crate"
format_code_in_doc_comments = true
